//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hausarbeit_Lager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warenausgang
    {
        public int WarenausgangID { get; set; }
        public int Kunde { get; set; }
        public int Artikel { get; set; }
        public int Bestellmenge { get; set; }
    
        public virtual Kunde Kunde1 { get; set; }
        public virtual Waren Waren { get; set; }
    }
}
